const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Behaviors.scrollto,
		C3.Behaviors.Fade,
		C3.Behaviors.destroy,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.IsTouchingObject
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{Solid: 0},
	{Tilemap: 0},
	{arah: 0},
	{"8Direction": 0},
	{BoundToLayout: 0},
	{Platform: 0},
	{Flash: 0},
	{ninja: 0},
	{Keyboard: 0},
	{ScrollTo: 0},
	{kamera: 0},
	{batas: 0},
	{suriken1: 0},
	{diamond: 0},
	{nyawa: 0},
	{Fade: 0},
	{DestroyOutsideLayout: 0},
	{musuh: 0},
	{Particles: 0},
	{Bullet: 0},
	{tembakan_musuh: 0},
	{tembakan_ninja: 0},
	{Touch: 0},
	{kunci: 0},
	{cek_kunci: 0},
	{portal: 0},
	{pijakan: 0},
	{text_judul: 0},
	{memulai: 0},
	{Audio: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{KALAH: 0},
	{Sine: 0},
	{bath: 0},
	{kamehame: 0},
	{buka_portal: 0},
	{health: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	ninja: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	kamera: class extends self.ISpriteInstance {},
	batas: class extends self.ISpriteInstance {},
	suriken1: class extends self.ISpriteInstance {},
	diamond: class extends self.ISpriteInstance {},
	musuh: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	nyawa: class extends self.ITextInstance {},
	tembakan_musuh: class extends self.ISpriteInstance {},
	tembakan_ninja: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	kunci: class extends self.ISpriteInstance {},
	cek_kunci: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	pijakan: class extends self.ISpriteInstance {},
	text_judul: class extends self.ITextInstance {},
	memulai: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	KALAH: class extends self.ITextInstance {},
	bath: class extends self.ISpriteInstance {}
}