const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.bound,
		C3.Behaviors.EightDir,
		C3.Behaviors.wrap,
		C3.Behaviors.Fade,
		C3.Behaviors.Orbit,
		C3.Behaviors.Sin,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Plugins.Touch,
		C3.Behaviors.scrollto,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject
	];
};
self.C3_JsPropNameTable = [
	{BackgroundHome: 0},
	{Text_Petualangan: 0},
	{ButtonStart: 0},
	{bgMain: 0},
	{BoundToLayout: 0},
	{"8Direction": 0},
	{Wrap: 0},
	{turtle: 0},
	{Fade: 0},
	{Orbit: 0},
	{Sine: 0},
	{fish: 0},
	{Solid: 0},
	{Physics: 0},
	{Batu: 0},
	{Sampah: 0},
	{Touch: 0},
	{scoreBoard: 0},
	{Text_score: 0},
	{bgEnd: 0},
	{highscoreBoard: 0},
	{btRetry: 0},
	{Text_total_score: 0},
	{ScrollTo: 0},
	{kamera: 0},
	{score_number: 0}
];

self.InstanceType = {
	BackgroundHome: class extends self.ISpriteInstance {},
	Text_Petualangan: class extends self.ITextInstance {},
	ButtonStart: class extends self.ISpriteInstance {},
	bgMain: class extends self.ISpriteInstance {},
	turtle: class extends self.ISpriteInstance {},
	fish: class extends self.ISpriteInstance {},
	Batu: class extends self.ISpriteInstance {},
	Sampah: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	scoreBoard: class extends self.ISpriteInstance {},
	Text_score: class extends self.ITextInstance {},
	bgEnd: class extends self.ISpriteInstance {},
	highscoreBoard: class extends self.ISpriteInstance {},
	btRetry: class extends self.ISpriteInstance {},
	Text_total_score: class extends self.ITextInstance {},
	kamera: class extends self.ISpriteInstance {}
}