const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Behaviors.bound,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Behaviors.scrollto,
		C3.Behaviors.Rotate,
		C3.Behaviors.Fade,
		C3.Behaviors.Timer,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{bg1: 0},
	{Sine: 0},
	{teksnjudul: 0},
	{start: 0},
	{klikDisini: 0},
	{"8Direction": 0},
	{charAwal: 0},
	{backgroundMain: 0},
	{Solid: 0},
	{Tilemap: 0},
	{arah: 0},
	{Platform: 0},
	{Flash: 0},
	{BoundTo: 0},
	{charInti: 0},
	{Touch: 0},
	{Audio: 0},
	{Keyboard: 0},
	{koin_txt: 0},
	{ScrollTo: 0},
	{kamera: 0},
	{skor: 0},
	{semanggi: 0},
	{Rotate: 0},
	{suriken: 0},
	{batas: 0},
	{Fade: 0},
	{Timer: 0},
	{musuh: 0},
	{Bullet: 0},
	{PELURU: 0},
	{nyawa: 0},
	{TiledBackground: 0},
	{petunjuk: 0},
	{semanggis: 0},
	{portal: 0},
	{kotak: 0},
	{nyawaHti: 0},
	{misi: 0},
	{smngpoin: 0},
	{rety: 0},
	{papan: 0},
	{totalTeksAkhir: 0},
	{totalnyawa: 0},
	{TiledBackground2: 0},
	{Text: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Text2: 0},
	{Text3: 0},
	{Sprite: 0},
	{Sprite5: 0},
	{koin: 0},
	{semanggipoin: 0},
	{target: 0}
];

self.InstanceType = {
	bg1: class extends self.ITiledBackgroundInstance {},
	teksnjudul: class extends self.ITextInstance {},
	start: class extends self.ISpriteInstance {},
	klikDisini: class extends self.ITextInstance {},
	charAwal: class extends self.ISpriteInstance {},
	backgroundMain: class extends self.ITiledBackgroundInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	charInti: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	koin_txt: class extends self.ITextInstance {},
	kamera: class extends self.ISpriteInstance {},
	skor: class extends self.ISpriteInstance {},
	semanggi: class extends self.ISpriteInstance {},
	suriken: class extends self.ISpriteInstance {},
	batas: class extends self.ISpriteInstance {},
	musuh: class extends self.ISpriteInstance {},
	PELURU: class extends self.ISpriteInstance {},
	nyawa: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	petunjuk: class extends self.ITextInstance {},
	semanggis: class extends self.ITextInstance {},
	portal: class extends self.ISpriteInstance {},
	kotak: class extends self.ISpriteInstance {},
	nyawaHti: class extends self.ISpriteInstance {},
	misi: class extends self.ITextInstance {},
	smngpoin: class extends self.ITextInstance {},
	rety: class extends self.ISpriteInstance {},
	papan: class extends self.ISpriteInstance {},
	totalTeksAkhir: class extends self.ITextInstance {},
	totalnyawa: class extends self.ITextInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {}
}